offer_user_offer:
    resource: "@OfferBundle/Resources/config/routing/user_offer.yml"
    prefix:   /usuario/ofertas

offer_public_offer:
    resource: "@OfferBundle/Resources/config/routing/offer.yml"
    prefix:   /ofertas
    
offer_contact_send:
    path:     /participa
    defaults: { _controller: "OfferBundle:Contact:contact" }

