offer_user_offer:
    resource: "@OfferBundle/Resources/config/routing/user_offer.yml"
    prefix:   /usuario/ofertas

offer_public_offer:
    resource: "@OfferBundle/Resources/config/routing/offer.yml"
    prefix:   /ofertas

