version: '2'
services:
  chatboilerplate:
    build: .
    volumes:
      - ".:/var/www/html/"
      - "/home/ping/.ssh/:/root/.ssh/"
    ports:
      - 80:80
    restart: always
    environment:
      - ENV=dev
      - PATH=/var/www/html/bin:$PATH
    container_name: chatboilerplate

networks:
  default:
    external:
      name: chatboilerplate
