ant_mans_terms_and_conditions:
    path: /terminos-y-condiciones
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'MansBundle:Static:terms_and_conditions.html.twig'
        maxAge:       86400
        sharedAge:    86400