client: 15
affiliate_name: 'Chat'
brand_image_url: 'http://www.chatearlatino.net/img/logo.png'
welcome_message: Bienvenido a nuestro chat
welcome_message_extended: A continuación podrás gestionar tu cuenta.