client: 15
affiliate_name: 'Chat'
brand_image_url: ''
welcome_message: Panel de usuario
welcome_message_extended: A continuación podrás gestionar tu cuenta, resetear contraseña, cambiar password y registrar sala.
chat_url: null
navbar_color: '#9ac02f'
email: contacto@antweb.es