parkimetro:
    path:     /
    defaults: { _controller: "ParkingBundle:ParkingTicket:index" }

parkimetro_show:
    path:     /{id}/ver
    defaults: { _controller: "ParkingBundle:ParkingTicket:show" }