parking:
    path:     /
    defaults: { _controller: "ParkingBundle:Parking:index" }

parking_show:
    path:     /{id}/show
    defaults: { _controller: "ParkingBundle:Parking:show" }

parking_new:
    path:     /new
    defaults: { _controller: "ParkingBundle:Parking:new" }

parking_create:
    path:     /create
    defaults: { _controller: "ParkingBundle:Parking:create" }
    requirements: { _method: post }

parking_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParkingBundle:Parking:edit" }

parking_update:
    path:     /{id}/update
    defaults: { _controller: "ParkingBundle:Parking:update" }
    requirements: { _method: post|put }

parking_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParkingBundle:Parking:delete" }
    requirements: { _method: post|delete }
