apiRequestAllow:
  api_users:
    url: "/api/users/{id}"
    fields: ['id',  'username', 'profile', 'username_canonical']

  api_outstanding_users:
    url: "/api/outstanding/{id}"
    fields: ['id',  'username', 'profile']


