dizda_cloud_backup:
    processor:
        type: tar
        date_format: 'Y/m/d/H-i-s'
    cloud_storages:
        gaufrette:
            service_name:   # Gaufrette filesystem(s) service name
                - amazon_backup_filesystem

    databases:
        mysql:


services:
    backup.aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                key: %amazon_s3.key%
                secret: %amazon_s3.secret%
                region: %amazon_s3.region%

knp_gaufrette:
    adapters:
        backup_adapter:
            aws_s3:
                service_id: backup.aws_s3.client
                bucket_name:  %amazon_backup_s3_bucket_name%
    filesystems:
        backup_adapter:
            adapter:    backup_adapter
            alias:      amazon_backup_filesystem