imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

twig:
    globals:
        bp_analytics_id: %analytics_id%
        social_endpoint: %social_endpoint%
        api_endpoint: %api_endpoint%
        payment_endpoint: %payment_endpoint%

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_endpoint%
            logging: %kernel.debug%
            
chatea_client:
    can_skip_register_profile: true