imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

twig:
    globals:
        bp_analytics_id: UA-41992080-4
        social_endpoint: %social_endpoint%
        payment_endpoint: %payment_endpoint%

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%redis_password%@%redis_host%/%redis_db%
            logging: %kernel.debug%
    session:
      client: default
      prefix: 'chat.boilerplate_'
      ttl: 3600