easy_admin:
    entities:
        Offer:
            class: Ant\Bundle\OfferBundle\Entity\Offer
            label: 'Ofertas'
            new:
                fields:
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'description', label: 'Descripción' }
                    - { property: 'owner', label: 'Usuario propietario' }
                    - { property: 'enabled', label: 'Habilitada' }
                    - { property: 'expiredAt', label: 'Expirará el..' }
        Parking:
            class: Ant\Bundle\ParkingBundle\Entity\Parking
            label: 'Parkings'
        ParkingTicket:
                    class: Ant\Bundle\ParkingBundle\Entity\ParkingTicket
                    label: 'ParkingTickets'
    site_name: 'Mans Networking'