parking:
    resource: "@ParkingBundle/Resources/config/routing.yml"
    prefix:   /

offer:
    resource: "@OfferBundle/Resources/config/routing.yml"
    prefix:   /

ant_api_social:
    resource: "@ApiSocialBundle/Resources/config/routing-es.yml"
    prefix:   /

ant_help_bundle:
    resource: "@HelpBundle/Resources/config/routing/routing-es.yml"
    prefix:   /ayuda

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

chatea_client_register_channel:
    path: /registrar-canal
    defaults: { _controller: AppBundle:ChateaClientChannel:register }
    
antwebes_chateclient:
    resource: '@ChateaClientBundle/Resources/config/routing/routing-es.xml'
    prefix:   / 

chatea_secure:
   resource: "@ChateaSecureBundle/Controller/SecuredController.php"
   prefix: /usuario
   type: annotation

core_api:
    path:  /api/{_resource}
    defaults: { _controller: AppBundle:Default:api }
    requirements:
        _resource:  .+

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin