security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_AFFILIATE: ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_AFFILIATE]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_AFFILIATE, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        antwebs_chateaclient_provider:
            id: antwebs_chateasecure_user_provider
        in_memory:
            memory:
                users:
                    admin:  { password: admin, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~
            pattern:    ^/
            anonymous: ~
            antwebs_chateasecure_login:
                check_path: _security_check
                login_path: _antwebes_chateaclient_login
                provider: antwebs_chateaclient_provider
            logout:
                invalidate_session: false
                path:   _antwebes_chateaclient_logout
                target: homepage
                handlers: [antwewebs_revoke_access_on_logout_handler]

    access_control:
        - { path: ^/usuarios/.*/fotos, roles: ROLE_USER }
        - { path: ^/perfil, roles: ROLE_USER }