vich_uploader:
    db_driver: orm
    mappings:
        offer_images:
            uri_prefix:         %app.path.offer_images%
            upload_destination: %kernel.root_dir%/../web/uploads/images/offers