parking_parkimetro:
    resource: "@ParkingBundle/Resources/config/routing/parkingticket.yml"
    prefix:   /parkimetro

parking_parking:
    resource: "@ParkingBundle/Resources/config/routing/parking.yml"
    prefix:   /parking

parking_user_parking:
    resource: "@ParkingBundle/Resources/config/routing/user_parking.yml"
    prefix:   /usuario/parking

parking_user_parking_ticket:
    resource: "@ParkingBundle/Resources/config/routing/user_parking_ticket.yml"
    prefix:   /usuario/parkimetro
    
parking_help:
    path: /ayuda/parking
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'ParkingBundle:Help:parking.html.twig'
